# Generated by Django 4.2.7 on 2024-01-17 19:23

import api_portfolio.models.project
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Project",
            fields=[
                ("ID", models.AutoField(primary_key=True, serialize=False)),
                ("Name", models.CharField(max_length=200)),
                ("Description", models.CharField(max_length=500)),
                ("Link", models.CharField(blank=True, max_length=500, null=True)),
                ("LinkGit", models.CharField(blank=True, max_length=500, null=True)),
                ("LinkBack", models.CharField(blank=True, max_length=500, null=True)),
                (
                    "LinkGitBack",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                (
                    "Imagem",
                    models.ImageField(upload_to=api_portfolio.models.project.nome_img),
                ),
            ],
        ),
    ]
