# Generated by Django 4.2.7 on 2024-01-17 20:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api_portfolio", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="Tags",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
